### ISSUE TITLE
Buttons to toggle mode on Lovelace

### ISSUE THREAD

**Issue by IamMrandrew** [maykar/kiosk-mode#35]
Hi, is there anyway I can implement a button to toggle the kiosk mode on lovelace.
I am thinking to create an input.boolean and toogle using template.

Here is my code which doesn't work :(
```
kiosk_mode:
  kiosk: >-
    {% if is_state('input_boolean.kiosk_mode', 'on') %}
      true
    {% else %}
      false
    {% endif %}
```
Any tips for me?

**Comment by IamMrandrew** [comment]
Also tried this, not working
```
kiosk_mode:
  kiosk: "{{ state('input_boolean.kiosk_mode') }}"
```
Found something, it work for the first time when page is refreshed after changing the ui-lovelace.yaml. I guess is it something about the cache?

**Comment by IamMrandrew** [comment]
Ok! I managed to solve it with [Template Switch](https://www.home-assistant.io/integrations/template/) and [browser_mod](https://github.com/thomasloven/hass-browser_mod)
Not the best solution but it works for now.

```
- platform: template
  switches:
    kiosk_mode:
      turn_on:
        - service: browser_mod.navigate
          data:
            navigation_path: /lovelace/homekit?kiosk
        - service: browser_mod.window_reload  
      turn_off:
        - service: browser_mod.navigate
          data:
            navigation_path: /lovelace/homekit?clear_km_cache
        - service: browser_mod.window_reload
```
