### ISSUE TITLE
Toggle kiosk mode from picture-elements

### ISSUE THREAD

**Issue by tbarbette** [maykar/kiosk-mode#40]
Hi all,

I have a picture element showing my floor plan, and I'd like a button to toggle kiosk mode. The following rewrite the URL but it does nothing:

```
  - type: icon
    icon: 'mdi:home'
    tap_action:
      action: navigate
      navigation_path: /lovelace/plan?kiosk
    style:
      right: 10%
      bottom: 10%
```

Any idea? And then it does not even support "toggling". It's for a raspberry pi touchscreen without keyboard, so when I go to kiosk mode I'm kind of locked on the floor plan.

**Comment by KTibow** [comment]
Use `browser_mod.window_reload`. And as for toggling, just reload again without the `?kiosk`.

**Comment by tbarbette** [comment]
I tried what was proposed on #35 and it did not work either:
```
- platform: template
  switches:
    kiosk_mode:
      turn_on:
        - service: browser_mod.navigate
          data:
            navigation_path: /lovelace/homekit?kiosk
        - service: browser_mod.window_reload  
      turn_off:
        - service: browser_mod.navigate
          data:
            navigation_path: /lovelace/homekit?disable_km
        - service: browser_mod.window_reload
```
It does nothing when I click. I use Chrome on windows.
