### ISSUE TITLE
Lovelace config not found

### ISSUE THREAD

**Issue by Pulpyyyy** [maykar/kiosk-mode#67]
Still have troubles hiding part of the UI .... Page loads in less than 15s with 1.7.0 but setting doesn't apply in non-admin

Error:
```
Lovelace config not found, continuing with default configuration.
```

Config is correct as reverting to 1.6.5 hides stuff correctly

```
kiosk_mode:
  admin_settings:
    hide_header: false
    hide_sidebar: false
    hide_overflow: false
  non_admin_settings:
    hide_header: false
    hide_sidebar: true
    hide_overflow: true
```
