### ISSUE TITLE
Kiosk mode not working after v1.6.5

### ISSUE THREAD

**Issue by henriklund** [maykar/kiosk-mode#68]
From v1.6.6 and onwards Kiosk mode no longer hides sidebar or header.

Visited from Chrom (incognito):
- Console shows 'version 1.6.7'
- the only warning I see is
`kiosk-mode.js?hacstag=303101606167:20 Lovelace config not found, continuing with default configuration.`
- Config
```
kiosk_mode:
  admin_settings:
    ignore_entity_settings: true
  non_admin_settings:
    hide_sidebar: true
    hide_header: true
    hide_overflow: true

```
- Devices affected are Windows (Chrome) and iPads (2x) iOS 14

Interestingly enough 1.6.5 shows following error:

```
kiosk-mode.js?hacstag=303101606165:37 Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at v (kiosk-mode.js?hacstag=303101606165:37)
    at k (kiosk-mode.js?hacstag=303101606165:37)
    at kiosk-mode.js?hacstag=303101606165:44
v @ kiosk-mode.js?hacstag=303101606165:37
k @ kiosk-mode.js?hacstag=303101606165:37
(anonymous) @ kiosk-mode.js?hacstag=303101606165:44
Promise.then (async)
(anonymous) @ kiosk-mode.js?hacstag=303101606165:43
```

**Comment by lue42** [comment]
Same as above:

Edge Version 91.0.864.59 on Windows 10, logged into HA as a "user"

Console shows 1.7.0
No warnings, Kiosk-Mode shows 1.7.0

```
kiosk_mode:
  non_admin_settings:
    hide_header: true
    hide_sidebar: true
```

It is not working on IOS 12.5.4 on iPhone 5s - I fully reset cache in Safari on phone.
